server:
  port: 8088
spring:
  application:
    name: service-zuul
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8084/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-cli1
    api-b:
      path: /api-b/**
      serviceId: service-feign